language: node_js

node_js:
- '4.4.3'

services:
  - docker

script: 
  - npm install
  - npm test
  - docker ps | grep -q vendingmachinekata 
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t joshmccall221/vendingmachinekata .
  - docker tag joshmccall221/vendingmachinekata joshmccall221/vendingmachinekata:'v.0.0'
  - docker run -d -p 127.0.0.1:80:80 --name vendingmachinekata joshmccall221/vendingmachinekata:'v.0.0'
  
after_success:
  - webpack
  - chmod a+x deploy-ghpages.sh
  - npm run-script deploy
  - docker push joshmccall221/vendingmachinekata
  - docker push joshmccall221/vendingmachinekata:$TRAVIS_BUILD_NUMBER

env:
 global:
 - GH_REF: github.com/McCallTech/vendingMachineKata.git
 - secure: JQI3KN7yurE4bzp2X9tuGxR7UCSNJpJpRQcSSxe0beHhY1zp11usi6vjpR50rve3R+V3luaXHDF6YoV6q8wDYcK6+2oDGSwxym+NtID8/X0cH2GuWzWRjDD3972VHsVbIr1UE1ltDZcM1ISznvgF7R7k4jPNOgaH3xF8tTIMIfxjRdR2+mi7KAg2Pb5+l7IO+m7Fy7e/SsCimffqUyVrV09fvdXFtxLCmbsgwPd2DREUNt+uuNVdb73S7xrr4SS867hjImML1CW4rrhBdSFYHGTAiLR7PnkHixbXru7p5qATOOEI4pUSgkEPZXFy2DewBuUqG1g4224Nymle5Uf42kErZYYn7HV4OuXRobW48Xulr+ALWFoBG3RantxjEeVvwyJVOkWkpirBO0/f5GB+JjtdTDBsgs457obVFwaaIggCNXrzTIH6dsPN2WWElRoK1xft2YdGkndzLu8JcLgETdzMdTckjdBznBZ1jJXxGzXVE+QY12S3iaUmSNB0jtT6k65Bm9p1pGeRiZnPxTmLUyGTls28fK9LVBJmGUnjMNFjPTe2UlxnZdOQi80qqmg526OZnlg3xAfY0MWce7N5bBqBHjxd2lFSiY/GVe8RPucorY8FZ7ZYSGdPDUtsVNmP9+dDqAcoGRPGJE1b4hTyxBJ0UMyM/XwIkFgioYTNKgI=
