#!/bin/bash

#apt-get update &&  apt-get install curl -y &&  curl -o- https://raw.githubusercontent.com/joshmccall221/dotfiles/master/salt >> salt && bash salt

wget -O - https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
echo 'deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main ' >> /etc/apt/sources.list.d/salt.list

sudo apt-get update -y

sudo apt-get install salt-minion -y

salt-call --local pkg.install git 
salt-call --local pkg.install make 
salt-call --local pkg.install vim 
salt-call --local pkg.install tmux 
salt-call --local pkg.install ack-grep 


mkdir /srv/salt
cd /srv/salt/
git clone https://github.com/saltstack-formulas/docker-formula.git
cp -R ./docker-formula/docker/ .
salt-call --local state.sls docker
#git clone https://github.com/joshmccall221/dotfiles.git
#cd dotfiles/
#make eclipse_che 
